import AboutContent from "../components/AboutContent";

export const metadata = {
    title: "About",
    description: "Generated by create next app",
  };
const aboutPage = () => {
    return (
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
            <div>
               <p className="text-6xl font-bold"> About Page</p>
                <AboutContent></AboutContent>

                </div>
        </main>
    );
};

export default aboutPage;