import { Merriweather } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const merriweather = Merriweather({
  weight: ["300","400", "700", "900" ] ,
  subsets: ["latin"] ,  
  preload: true, 
});

export const metadata = {
  title: {
    default: "Next js",
    template: "%s | Next js"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={merriweather.className}>
      <Navbar></Navbar>
        {children}
        </body>
    </html>
  );
}
